services:
  - type: web
    name: carpool-app
    env: node
    region: singapore
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: carpool-db
          property: connectionString

databases:
  - name: carpool-db
    databaseName: carpool
    region: singapore
    plan: free